### ISSUE TITLE
Which 19,466 audio files do you choose from FMA？

### ISSUE THREAD

**Issue by Aolin-MIR** [kunimi00/ZSL_music_tagging#3]
According to the paper, you chose 19466 audio from FMA. I downloaded the corpus, but don't know the order of the chosen 19466 audio files corresponding to the resource files. Please provide it to me. Thanks.

**Comment by Aolin-MIR** [comment]
have found it

**Comment by kunimi00** [comment]
Dear @liaolin  I'm really sorry for missing this thread..! Glad that u figured out. Please feel free to ask any further questions. I'll try to be more responsive this time.
